import type { Metadata } from "next";
import { Providers } from "./providers";
import { gilroy } from "@/components/ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        style={{
          height: "100dvh",
          backgroundColor: "#FFFFFF",
          color: "#000000",
          fontStyle: "normal",
          fontWeight: "500",
        }}
        className={gilroy.className}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
